name: archie
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  dio: ^5.7.0
  #Service Request

  flutter_bloc: ^8.1.6
  #State Management

  go_router: ^14.6.2
  meta: ^1.15.0
  bloc: ^8.1.4
  #Page Navigation  

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true